import { useState, useRef } from "react";
import { useNavigate } from "react-router-dom";
import { Layout } from "@/components/layout/Layout";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Label } from "@/components/ui/label";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useToast } from "@/hooks/use-toast";
import { supabase } from "@/integrations/supabase/client";
import { 
  Mic, 
  MicOff, 
  Upload, 
  MapPin, 
  FileText, 
  Image as ImageIcon,
  Video,
  X,
  Loader2,
  CheckCircle2,
  AlertTriangle
} from "lucide-react";
import { CATEGORY_LABELS, PRIORITY_LABELS, ComplaintCategory, ComplaintPriority } from "@/lib/types";

export default function ReportIssue() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const fileInputRef = useRef<HTMLInputElement>(null);
  
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [isRecording, setIsRecording] = useState(false);
  const [submittedId, setSubmittedId] = useState<string | null>(null);
  
  const [formData, setFormData] = useState({
    category: "" as ComplaintCategory | "",
    priority: "medium" as ComplaintPriority,
    description: "",
    address: "",
    location_lat: null as number | null,
    location_lng: null as number | null,
    email: "",
  });
  
  const [files, setFiles] = useState<File[]>([]);
  const [voiceText, setVoiceText] = useState("");

  const handleGetLocation = () => {
    if ("geolocation" in navigator) {
      navigator.geolocation.getCurrentPosition(
        (position) => {
          setFormData(prev => ({
            ...prev,
            location_lat: position.coords.latitude,
            location_lng: position.coords.longitude,
          }));
          toast({
            title: "Location detected",
            description: "Your current location has been added to the report.",
          });
        },
        (error) => {
          toast({
            variant: "destructive",
            title: "Location error",
            description: "Unable to get your location. Please enter address manually.",
          });
        }
      );
    }
  };

  const handleFileChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const newFiles = Array.from(e.target.files || []);
    if (files.length + newFiles.length > 5) {
      toast({
        variant: "destructive",
        title: "Too many files",
        description: "You can upload a maximum of 5 files.",
      });
      return;
    }
    setFiles(prev => [...prev, ...newFiles]);
  };

  const removeFile = (index: number) => {
    setFiles(prev => prev.filter((_, i) => i !== index));
  };

  const handleVoiceRecording = () => {
    if (!("webkitSpeechRecognition" in window) && !("SpeechRecognition" in window)) {
      toast({
        variant: "destructive",
        title: "Not supported",
        description: "Voice recording is not supported in your browser.",
      });
      return;
    }

    const SpeechRecognition = (window as any).SpeechRecognition || (window as any).webkitSpeechRecognition;
    const recognition = new SpeechRecognition();
    
    recognition.continuous = true;
    recognition.interimResults = true;

    if (isRecording) {
      recognition.stop();
      setIsRecording(false);
    } else {
      setIsRecording(true);
      recognition.start();
      
      recognition.onresult = (event: any) => {
        let transcript = "";
        for (let i = 0; i < event.results.length; i++) {
          transcript += event.results[i][0].transcript;
        }
        setVoiceText(transcript);
        setFormData(prev => ({
          ...prev,
          description: prev.description + " " + transcript,
        }));
      };

      recognition.onerror = () => {
        setIsRecording(false);
        toast({
          variant: "destructive",
          title: "Recording error",
          description: "There was an error with voice recording.",
        });
      };

      recognition.onend = () => {
        setIsRecording(false);
      };
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!formData.category || !formData.description) {
      toast({
        variant: "destructive",
        title: "Missing information",
        description: "Please select a category and provide a description.",
      });
      return;
    }

    setIsSubmitting(true);

    try {
      // Get current user (optional)
      const { data: { user } } = await supabase.auth.getUser();

      // Create complaint (complaint_id is auto-generated by database trigger)
      const { data: complaint, error: complaintError } = await supabase
        .from("complaints")
        .insert({
          category: formData.category,
          priority: formData.priority,
          description: formData.description,
          text_from_voice: voiceText || null,
          address: formData.address || null,
          location_lat: formData.location_lat,
          location_lng: formData.location_lng,
          user_id: user?.id || null,
        } as any)
        .select()
        .single();

      if (complaintError) throw complaintError;

      // Create initial status update
      await supabase.from("status_updates").insert({
        complaint_id: complaint.id,
        status: "pending",
        remarks: "Complaint registered successfully",
        updated_by: user?.id || null,
      });

      setSubmittedId(complaint.complaint_id);

      // Send email notification if email provided
      if (formData.email) {
        try {
          await supabase.functions.invoke('send-complaint-confirmation', {
            body: {
              email: formData.email,
              complaintId: complaint.complaint_id,
              category: CATEGORY_LABELS[formData.category as ComplaintCategory],
              description: formData.description,
              address: formData.address,
            },
          });
        } catch (emailError) {
          console.error("Email notification failed:", emailError);
        }
      }
      
      toast({
        title: "Complaint submitted!",
        description: `Your tracking ID is: ${complaint.complaint_id}`,
      });

    } catch (error: any) {
      console.error("Submit error:", error);
      toast({
        variant: "destructive",
        title: "Submission failed",
        description: error.message || "Please try again later.",
      });
    } finally {
      setIsSubmitting(false);
    }
  };

  if (submittedId) {
    return (
      <Layout>
        <div className="container py-16 md:py-24">
          <Card className="max-w-lg mx-auto text-center border-0 shadow-xl">
            <CardContent className="p-10">
              <div className="w-20 h-20 rounded-full bg-status-resolved/10 flex items-center justify-center mx-auto mb-6">
                <CheckCircle2 className="h-10 w-10 text-status-resolved" />
              </div>
              <h2 className="text-2xl font-display font-bold mb-2">Complaint Submitted!</h2>
              <p className="text-muted-foreground mb-6">
                Your complaint has been registered successfully. Save your tracking ID to monitor progress.
              </p>
              <div className="bg-muted rounded-lg p-4 mb-6">
                <p className="text-sm text-muted-foreground mb-1">Tracking ID</p>
                <p className="text-2xl font-mono font-bold text-civic-navy">{submittedId}</p>
              </div>
              <div className="flex flex-col sm:flex-row gap-3">
                <Button variant="civic" className="flex-1" onClick={() => navigate(`/track?id=${submittedId}`)}>
                  Track Complaint
                </Button>
                <Button variant="outline" className="flex-1" onClick={() => {
                  setSubmittedId(null);
                  setFormData({
                    category: "",
                    priority: "medium",
                    description: "",
                    address: "",
                    location_lat: null,
                    location_lng: null,
                    email: "",
                  });
                  setFiles([]);
                  setVoiceText("");
                }}>
                  Report Another
                </Button>
              </div>
            </CardContent>
          </Card>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="container py-8 md:py-12">
        <div className="max-w-3xl mx-auto">
          <div className="text-center mb-8">
            <h1 className="text-3xl md:text-4xl font-display font-bold mb-2">Report a Civic Issue</h1>
            <p className="text-muted-foreground">
              Help improve your community by reporting infrastructure problems
            </p>
          </div>

          <form onSubmit={handleSubmit}>
            <Card className="border-0 shadow-lg mb-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <FileText className="h-5 w-5 text-civic-teal" />
                  Issue Details
                </CardTitle>
                <CardDescription>Describe the problem you want to report</CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                <div className="grid md:grid-cols-2 gap-4">
                  <div className="space-y-2">
                    <Label htmlFor="category">Category *</Label>
                    <Select
                      value={formData.category}
                      onValueChange={(value: ComplaintCategory) => setFormData(prev => ({ ...prev, category: value }))}
                    >
                      <SelectTrigger>
                        <SelectValue placeholder="Select category" />
                      </SelectTrigger>
                      <SelectContent>
                        {Object.entries(CATEGORY_LABELS).map(([value, label]) => (
                          <SelectItem key={value} value={value}>{label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                  <div className="space-y-2">
                    <Label htmlFor="priority">Priority</Label>
                    <Select
                      value={formData.priority}
                      onValueChange={(value: ComplaintPriority) => setFormData(prev => ({ ...prev, priority: value }))}
                    >
                      <SelectTrigger>
                        <SelectValue />
                      </SelectTrigger>
                      <SelectContent>
                        {Object.entries(PRIORITY_LABELS).map(([value, label]) => (
                          <SelectItem key={value} value={value}>{label}</SelectItem>
                        ))}
                      </SelectContent>
                    </Select>
                  </div>
                </div>

                <div className="space-y-2">
                  <Label htmlFor="email">Email (for notifications)</Label>
                  <Input
                    id="email"
                    type="email"
                    placeholder="Enter your email to receive updates"
                    value={formData.email}
                    onChange={(e) => setFormData(prev => ({ ...prev, email: e.target.value }))}
                  />
                </div>

                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <Label htmlFor="description">Description *</Label>
                    <Button
                      type="button"
                      variant={isRecording ? "destructive" : "outline"}
                      size="sm"
                      onClick={handleVoiceRecording}
                    >
                      {isRecording ? <MicOff className="h-4 w-4 mr-1" /> : <Mic className="h-4 w-4 mr-1" />}
                      {isRecording ? "Stop Recording" : "Voice Input"}
                    </Button>
                  </div>
                  <Textarea
                    id="description"
                    placeholder="Describe the issue in detail..."
                    className="min-h-[120px]"
                    value={formData.description}
                    onChange={(e) => setFormData(prev => ({ ...prev, description: e.target.value }))}
                  />
                  {isRecording && (
                    <p className="text-sm text-status-pending flex items-center gap-1">
                      <span className="w-2 h-2 rounded-full bg-status-pending animate-pulse" />
                      Recording... Speak now
                    </p>
                  )}
                </div>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg mb-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <MapPin className="h-5 w-5 text-civic-teal" />
                  Location
                </CardTitle>
                <CardDescription>Where is this issue located?</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="flex gap-2">
                  <Button type="button" variant="outline" onClick={handleGetLocation}>
                    <MapPin className="h-4 w-4 mr-1" />
                    Detect My Location
                  </Button>
                  {formData.location_lat && (
                    <span className="text-sm text-muted-foreground flex items-center">
                      <CheckCircle2 className="h-4 w-4 text-status-resolved mr-1" />
                      Location detected
                    </span>
                  )}
                </div>
                <div className="space-y-2">
                  <Label htmlFor="address">Address / Landmark</Label>
                  <Input
                    id="address"
                    placeholder="Enter address or nearby landmark"
                    value={formData.address}
                    onChange={(e) => setFormData(prev => ({ ...prev, address: e.target.value }))}
                  />
                </div>
              </CardContent>
            </Card>

            <Card className="border-0 shadow-lg mb-6">
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Upload className="h-5 w-5 text-civic-teal" />
                  Attachments
                </CardTitle>
                <CardDescription>Upload photos or videos (max 5 files)</CardDescription>
              </CardHeader>
              <CardContent>
                <div
                  className="border-2 border-dashed rounded-lg p-8 text-center cursor-pointer hover:border-civic-teal transition-colors"
                  onClick={() => fileInputRef.current?.click()}
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    multiple
                    accept="image/*,video/*"
                    className="hidden"
                    onChange={handleFileChange}
                  />
                  <div className="flex justify-center gap-4 mb-4">
                    <ImageIcon className="h-8 w-8 text-muted-foreground" />
                    <Video className="h-8 w-8 text-muted-foreground" />
                  </div>
                  <p className="text-sm font-medium mb-1">Click to upload files</p>
                  <p className="text-xs text-muted-foreground">Images and videos up to 50MB each</p>
                </div>

                {files.length > 0 && (
                  <div className="mt-4 space-y-2">
                    {files.map((file, index) => (
                      <div key={index} className="flex items-center justify-between p-2 bg-muted rounded-lg">
                        <div className="flex items-center gap-2">
                          {file.type.startsWith("image/") ? (
                            <ImageIcon className="h-4 w-4 text-muted-foreground" />
                          ) : (
                            <Video className="h-4 w-4 text-muted-foreground" />
                          )}
                          <span className="text-sm truncate max-w-[200px]">{file.name}</span>
                        </div>
                        <Button type="button" variant="ghost" size="icon" onClick={() => removeFile(index)}>
                          <X className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>

            <div className="flex gap-4">
              <Button type="submit" variant="civic" size="lg" className="flex-1" disabled={isSubmitting}>
                {isSubmitting ? (
                  <>
                    <Loader2 className="h-4 w-4 animate-spin" />
                    Submitting...
                  </>
                ) : (
                  <>
                    <FileText className="h-4 w-4" />
                    Submit Report
                  </>
                )}
              </Button>
            </div>
          </form>
        </div>
      </div>
    </Layout>
  );
}
